name: terminal
services:
  reverse-proxy:
    container_name: terminal.reverseproxy
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Config/nginx:/etc/nginx/:ro
      - ./Config/cert:/etc/ssl/:ro
    depends_on: [server, client]

  client:
    container_name: terminal.client
    build: "./Client"
    depends_on: ["server"]

  server:
    container_name: terminal.server
    build: "./Server/src"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5006
      - Jwt__Issuer=terminal
      - Jwt__Audience=terminal-clients
      - Jwt__SecretKey=[super-secret-key-for-development-purposes-only]
      - Postgres__ConnectionString=Host=database;Database=terminal;Username=root;Password=root;Include Error Detail=true
      - Administrator__Email=admin@terminal.com
      - Administrator__Password=password
    depends_on: ["database"]

  database:
    container_name: terminal.postgres
    image: postgres
    volumes:
      - ~/terminalData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=terminal
      - POSTGRES_USER=root
    pull_policy: missing
