name: CI - Client

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  client-ci:
    uses: ./.github/actions/terminal-client-ci.yml
    with:
      working_dir: Client
      node_version: 23
