name: CI for client

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  NODE_VERSION: "23"
  CLIENT_DIR: Client
  DOCS_DIR: Client/docs

defaults:
  run:
    working-directory: Client

jobs:
  build-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build client
        run: npm run build --if-present

      - name: Test client
        run: npm test --if-present

      - name: Lint code
        run: npm run lint

      - name: Format code
        run: npm run format

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        if: always()
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"

  make-docs:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [build-validation]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npx typedoc

      - name: Upload TypeDoc artifact
        uses: actions/upload-artifact@v4
        with:
          name: typedoc
          path: ${{ env.DOCS_DIR }}
