name: Build docker images

on:
  workflow_run:
    workflows: [Create release from tag]
    types:
      - completed

  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    needs: [build-and-push-images]
    uses: ./.github/workflows/terminal-ansible.yml
    secrets:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      ansible-user: ${{ secrets.ANSIBLE_USER }}
      deployment-targets: ${{ secrets.DEPLOYMENT_TARGETS }}
