name: Build docker images

on:
  push:
    branches: [feature/deploy]

  workflow_dispatch:

permissions: write-all

jobs:
  # client-build-validation:
  #   uses: ./.github/workflows/terminal-client-ci.yml
  # server-build-validation:
  #   uses: ./.github/workflows/terminal-server-ci.yml
  # build-and-push-images:
  #   uses: ./.github/workflows/terminal-docker.yml
  #   needs: [client-build-validation, server-build-validation]
  #   with:
  #     registry-url: ghcr.io
  #     registry-username: ${{ github.actor }}
  #   secrets:
  #     registry-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    uses: ./.github/workflows/terminal-ansible.yml
    secrets:
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      ansible-user: ${{ secrets.ANSIBLE_USER }}
      deployment-targets: ${{ secrets.DEPLOYMENT_TARGETS }}
