name: Build docker images

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  REGISTRY_NAME: ghcr.io

permissions: write-all

jobs:
  client-build-validation:
    uses: ./.github/actions/terminal-client-ci.yml
    with:
      working_dir: Client
      node_version: 23
  server-build-validation:
    uses: ./,github/actions/terminal-server-ci.yml
    with:
      working_dir: Server
      dotnet_version: 9.0.x
  build-and-push-images:
    runs-on: ubuntu-latest
    needs: [client-build-validation, server-build-validation]
    strategy:
      fail-fast: true
      matrix:
        include:
          - image-name: client
            context: ./Client
          - image-name: server
            context: ./Server/src
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Extract release version
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAME }}/${{ env.REPO_LC }}/${{ matrix.image-name }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=semver,pattern=v{{version}}

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
