name: Generate TypeDoc Documentation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
      
    - name: Install dependencies
      run: npm install
      working-directory: Client

    - name: Generate documentation
      run: npx typedoc
      working-directory: Client

    - name: Upload TypeDoc artifact
      uses: actions/upload-artifact@v4
      with:
        name: typedoc
        path: Client/docs
