name: Create release from tag

on:
  push:
    tags: ["v*"]

permissions: write-all

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract tag
        shell: bash
        id: create-tag
        run: |
          TAG=${GITHUB_REF#/refs/tags/}
          echo "Extracted tag: $TAG"
          echo -e "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_REF: ${{ github.ref }}
      - name: Verify tag comes from main branch
        shell: bash
        run: |
          COMMIT_HASH=$(git rev-parse --verify $RELEASE_TAG)
          BRANCHES_WITH_COMMIT=$(git branch -r --contains "$COMMIT_HASH" | sed 's/^[ \t]*//;s/[ \t]*$//')

          if echo "$BRANCHES_WITH_COMMIT" | grep -qx "origin/$DEFAULT_BRANCH"; then
              echo "✅ Tag from main!"
              exit 0
          else
              echo "⛔️ Tag not from main!"
              exit 1
          fi
        env:
          RELEASE_TAG: ${{ steps.create-tag.outputs.tag }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      - name: Create release
        shell: bash
        run: |
          echo "Creating release for tag $RELEASE_TAG"
          gh release create "$RELEASE_TAG" \
            --repo "$GITHUB_REPOSITORY" \
            --title "$RELEASE_TAG" \
            --generate-notes
        env:
          RELEASE_TAG: ${{ steps.create-tag.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
