name: CI for server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  server-ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Server build validation"
        uses: ./.github/actions/terminal-server-ci.yml
        with:
          working_dir: Server
          dotnet_version: 9.0.x
