on:
  workflow_call:
    inputs:
      dotnet_version:
        required: false
        type: string
        default: 9.0.x

defaults:
  run:
    working-directory: ./Server

jobs:
  build-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
